apiVersion: batch/v1beta1
kind: CronJob
metadata:
  namespace: rads
  name: rads-cli
spec:
  concurrencyPolicy: Replace
  # UTC なので 9時間マイナス
  #schedule: "54 5 * * *"
  schedule: "0 9 1-3 * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: rads-blue
            image: utiuti12345/rads-cli:0.1.10
            command: ["/bin/sh", "-c"]
            args: ["/work/rads.sh ${HOST} ${FOLDER}"]
            env:
              - name: HOST
                value: "http://10.0.1.6:1323"
              - name: FOLDER
                value: "勤務表"
          restartPolicy: OnFailure
      backoffLimit: 3
